name: cto_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  dio: ^5.0.0
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.0
  shared_preferences: ^2.0.0
  intl: ^0.18.0
  google_fonts: ^5.0.0
  file_picker: ^8.0.5
  url_launcher: ^6.1.11
  path_provider: ^2.1.5
  flex_color_scheme: ^8.3.1
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  flutter_foreground_task: ^9.1.0
  http: ^1.6.0
  tray_manager: ^0.5.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/summary-logo.webp

flutter_launcher_icons:
  image_path: assets/logo.png
  android: true
  ios: true
  macos:
    generate: true
    image_path: assets/logo.png
  windows:
    generate: true
    image_path: assets/logo.png
